use std::sync::LazyLock;

use crate::propindex::PropIndex;

/// The embedded property map. `propmap.bin` is generated by `wingschema` (`embed` or a live
/// sweep); see `propindex.rs` for its layout. Hand-written: only the blob is regenerated.
pub(crate) static NAME_TO_DEF: LazyLock<PropIndex> =
    LazyLock::new(|| PropIndex::new(include_bytes!("propmap.bin")));
